# <center>R para Geociencias: Aplicado a la hidrología</center>

### <center>Por: Víctor Rojas</center>

<img src="img/gmail_logo.png" height="30" width="30"> <center>vr.rojaspozo@gmail.com</center>

[<img  src="img/github_logo.png" height="30" width="30">](http://github.com/vrrp)
<center> vrrp </center>

## 3. Estructura de datos
* Listas
* Vectores
* Matrices

### 3.1 Listas

In [2]:
lista1 <- list(1,2,3,4)
lista1



[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

[[4]]
[1] 4

In [3]:
lista2 <- list(1,"hola", 1+1i)
lista2
length(lista2)

[[1]]
[1] 1

[[2]]
[1] "hola"

[[3]]
[1] 1+1i

[1] 3

In [4]:
lista3 <- 1:10
lista3
lista3[3]

length(lista3)
typeof(lista3)
class(lista3)

[1]  1  2  3  4  5  6  7  8  9 10

[1] 3

[1] 10

[1] "integer"

[1] "integer"

### 3.2 Vectores

In [6]:
vector1 <- c(1,2,3,4)
dim(vector1)
length(vector1)
typeof(vector1)

NULL

[1] 4

[1] "double"

In [7]:
vector2 <- c(20:24)
vector2

vector2[1]
vector2[4]

[1] 20 21 22 23 24

[1] 20

[1] 23

In [8]:
vector4<- c(TRUE, FALSE, FALSE, TRUE)
vector4[3]
typeof(vector4)
length(vector)

[1] FALSE

[1] "logical"

[1] 1

In [9]:
vector5 <- c("UTEC", 2020, "CITA")
vector5[2]
typeof(vector5)
length(vector5)

[1] "2020"

[1] "character"

[1] 3

In [10]:
vector_nan = c(NA, NA, NA)
vector_nan 
is.na(vector_nan)

vector_nan[1]<-11
vector_nan
is.na(vector_nan)
anyNA(vector_nan)

[1] NA NA NA

[1] TRUE TRUE TRUE

[1] 11 NA NA

[1] FALSE  TRUE  TRUE

[1] TRUE

### 3.3 Matrices

In [11]:
array1 =matrix(nrow=2, ncol=4)*2
array1
dim(array1)

array1[1,3]<-22
array1

[,1] [,2] [,3] [,4]
[1,] NA   NA   NA   NA  
[2,] NA   NA   NA   NA

[1] 2 4

[,1] [,2] [,3] [,4]
[1,] NA   NA   22   NA  
[2,] NA   NA   NA   NA

In [13]:
#array2 =matrix(1:12, nrow=3, ncol=4)*2
#
array2 =matrix(1:12, 3, 4)*2
array2

ndim <-  dim(array2)
nrows <- ndim[1]
ncols <- ndim[2]
nrows
ncols

typeof(ndim)
class(ndim)

[,1] [,2] [,3] [,4]
[1,] 2     8   14   20  
[2,] 4    10   16   22  
[3,] 6    12   18   24

[1] 3

[1] 4

[1] "integer"

[1] "integer"