# <center>R para Geociencias: Aplicado a la hidrología</center>

### <center>Por: Víctor Rojas</center>

<img src="img/gmail_logo.png" height="30" width="30"> <center>vr.rojaspozo@gmail.com</center>

[<img  src="img/github_logo.png" height="30" width="30">](http://github.com/vrrp)
<center> vrrp </center>

## 5. Control de flujos y matrices de 2D y 3D
### 5.1 Matrices de 2D

In [24]:
M1 =matrix(1:16, nrow=4, ncol=4)

print(M1)

ndim <-dim(M1)
nrows <- ndim[1]
ncols <- ndim[2]

cat("\n ndim(array1) = ", ndim)
cat("\n\n nrows(array1) = ", nrows)
cat("\n ncols(array1) = ", ncols)

     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    6   10   14
[3,]    3    7   11   15
[4,]    4    8   12   16

 ndim(array1) =  4 4

 nrows(array1) =  4
 ncols(array1) =  4

In [25]:
for(irow in 1:nrows){
    for (icol in 1:ncols){
        cat("\nM1[", irow,",",icol,"] --> ",M1[irow,icol] )
    }
}


M1[ 1 , 1 ] -->  1
M1[ 1 , 2 ] -->  5
M1[ 1 , 3 ] -->  9
M1[ 1 , 4 ] -->  13
M1[ 2 , 1 ] -->  2
M1[ 2 , 2 ] -->  6
M1[ 2 , 3 ] -->  10
M1[ 2 , 4 ] -->  14
M1[ 3 , 1 ] -->  3
M1[ 3 , 2 ] -->  7
M1[ 3 , 3 ] -->  11
M1[ 3 , 4 ] -->  15
M1[ 4 , 1 ] -->  4
M1[ 4 , 2 ] -->  8
M1[ 4 , 3 ] -->  12
M1[ 4 , 4 ] -->  16

In [26]:
for(irow in 1:nrows){
    for (icol in 1:ncols){
        if (irow==icol){
            M1[irow,icol]=1
        }
    }
}
print(M1)

     [,1] [,2] [,3] [,4]
[1,]    1    5    9   13
[2,]    2    1   10   14
[3,]    3    7    1   15
[4,]    4    8   12    1


In [27]:
for(irow in 1:nrows){
    for (icol in 1:ncols){
        if (M1[irow,icol]<10){
            M1[irow,icol]=NA
        }
    }
}
print(M1)

     [,1] [,2] [,3] [,4]
[1,]   NA   NA   NA   13
[2,]   NA   NA   10   14
[3,]   NA   NA   NA   15
[4,]   NA   NA   12   NA


# 5.2 Matrices 3D

In [77]:
M1 =array(1: 4*3*2, dim=c(4,3,2) )

print(M1[ , ,1]*3)
print(M1[ , ,2]*0.3)
 
ndim <-dim(M1)
nrows <- ndim[1]
ncols <- ndim[2]
nlevs <- ndim[3]

cat("\n ndim(array1) = ", ndim)
cat("\n\n nrows(array1) = ", nrows)
cat("\n ncols(array1) = ", ncols)
cat("\n nlevs(array1) = ", nlevs)
cat("\n", typeof(M1))
cat("\n", class(M1))

     [,1] [,2] [,3]
[1,]   18   18   18
[2,]   36   36   36
[3,]   54   54   54
[4,]   72   72   72
     [,1] [,2] [,3]
[1,]  1.8  1.8  1.8
[2,]  3.6  3.6  3.6
[3,]  5.4  5.4  5.4
[4,]  7.2  7.2  7.2

 ndim(array1) =  4 3 2

 nrows(array1) =  4
 ncols(array1) =  3
 nlevs(array1) =  2
 double
 array

In [78]:
print(M1)

for (ilev in 1:nlevs){
    if(ilev==1){
        for (irow in 1:nrows){
            for (icol in 1:ncols){
                if(M1[irow, icol, ilev]<17){
                    M1[irow, icol, ilev]=NA
                    }
             }
        }
    }
    else{
        for (irow in 1:nrows){
            for (icol in 1:ncols){
                if(M1[irow, icol, ilev]>12){
                    M1[irow, icol, ilev]=0
                    }
             }
        }
        
    }
}
print(M1)

, , 1

     [,1] [,2] [,3]
[1,]    6    6    6
[2,]   12   12   12
[3,]   18   18   18
[4,]   24   24   24

, , 2

     [,1] [,2] [,3]
[1,]    6    6    6
[2,]   12   12   12
[3,]   18   18   18
[4,]   24   24   24

, , 1

     [,1] [,2] [,3]
[1,]   NA   NA   NA
[2,]   NA   NA   NA
[3,]   18   18   18
[4,]   24   24   24

, , 2

     [,1] [,2] [,3]
[1,]    6    6    6
[2,]   12   12   12
[3,]    0    0    0
[4,]    0    0    0



In [81]:
print(M1[4,1,1:2])

[1] 24  0


In [83]:
print(M1[1,1,1:2])

[1] NA  6


In [85]:
print(M1[1,1:3,1])

[1] NA NA NA


In [86]:
print(M1[1:4,1,1])

[1] NA NA 18 24
